# Generated by Django 6.1.1 on 2026-09-15 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'item_details',
            },
        ),
        migrations.CreateModel(
            name='ElectronicsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True)),
                ('imei', models.CharField(blank=True, max_length=50, null=True)),
                ('item_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electronics', to='lost.itemdetails')),
            ],
            options={
                'db_table': 'electronics_details',
            },
        ),
        migrations.CreateModel(
            name='DocumentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('issuing_authority', models.CharField(blank=True, max_length=200, null=True)),
                ('item_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='lost.itemdetails')),
            ],
            options={
                'db_table': 'document_details',
            },
        ),
        migrations.CreateModel(
            name='ClothingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('item_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clothing', to='lost.itemdetails')),
            ],
            options={
                'db_table': 'clothing_details',
            },
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('edition', models.CharField(blank=True, max_length=100, null=True)),
                ('item_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='lost.itemdetails')),
            ],
            options={
                'db_table': 'book_details',
            },
        ),
        migrations.CreateModel(
            name='BagDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('item_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bag', to='lost.itemdetails')),
            ],
            options={
                'db_table': 'bag_details',
            },
        ),
        migrations.CreateModel(
            name='KeyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(blank=True, max_length=100, null=True)),
                ('keychain', models.CharField(blank=True, max_length=200, null=True)),
                ('item_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key', to='lost.itemdetails')),
            ],
            options={
                'db_table': 'key_details',
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('lost_date', models.DateField()),
                ('lost_location', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found'), ('CLAIMED', 'Claimed'), ('CLOSED', 'Closed')], default='LOST', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lost_items', to='lost.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lost_items',
            },
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='lost_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='lost.lostitem'),
        ),
        migrations.CreateModel(
            name='PersonalVerificationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_verification_questions',
            },
        ),
    ]
