# Generated by Django 6.1.1 on 2026-09-27 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lost', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemmatch',
            name='found_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_found', to='lost.lostitem'),
        ),
        migrations.AddField(
            model_name='itemmatch',
            name='lost_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_lost', to='lost.lostitem'),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='lost_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='lost.lostitem'),
        ),
        migrations.AddField(
            model_name='personalverificationquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='itemmatch',
            constraint=models.UniqueConstraint(fields=('lost_item', 'found_item'), name='unique_lost_found_match'),
        ),
    ]
