# Generated by Django 6.1.1 on 2026-09-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalverificationquestion',
            name='answer',
        ),
        migrations.AddField(
            model_name='personalverificationquestion',
            name='answer_hash',
            field=models.CharField(default=2, max_length=128),
            preserve_default=False,
        ),
    ]
