# Generated by Django 6.1.1 on 2026-09-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0002_remove_personalverificationquestion_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='status',
            field=models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found'), ('CLAIMED', 'Claimed'), ('CLOSED', 'Closed')], max_length=30),
        ),
        migrations.AlterModelTable(
            name='lostitem',
            table='items',
        ),
    ]
